# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
